name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Move files to bundle
        run: |
          mkdir bundle
          cp ./target/release/forgot ./bundle/forgot
          cp ./LICENSE ./bundle/LICENSE
          cp ./README.md ./bundle/README.md
      - name: Tar files
        run: tar -czvf ./forgot-${{ matrix.os }}-x86-64.tar.gz bundle
      - name: Upload bundle
        uses: actions/upload-artifact@v3.1.0
        with:
          name: forgot-${{ matrix.os }}.tar.gz
          path: ./forgot-${{ matrix.os }}-x86-64.tar.gz